# Generated by Django 4.2.3 on 2023-07-25 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)])),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=266)),
                ('age', models.FloatField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)])),
                ('income', models.FloatField(validators=[django.core.validators.MinValueValidator(1000)])),
                ('profession', models.CharField(choices=[('mechanical_engineer', 'MECHANICAL_ENGINEER'), ('software_developer', 'SOFTWARE_DEVELOPER'), ('technical_writer', 'TECHNICAL_WRITER'), ('civil_servant', 'CIVIL_SERVANT'), ('librarian', 'LIBRARIAN'), ('economist', 'ECONOMIST'), ('flight_attendant', 'FLIGHT_ATTENDANT'), ('architect', 'ARCHITECT'), ('designer', 'DESIGNER'), ('physician', 'PHYSICIAN'), ('financial_analyst', 'FINANCIAL_ANALYST'), ('air_traffic_controller', 'AIR_TRAFFIC_CONTROLLER'), ('politician', 'POLITICIAN'), ('police_officer', 'POLICE_OFFICER'), ('artist', 'ARTIST'), ('surveyor', 'SURVEYOR'), ('design_engineer', 'DESIGN_ENGINEER'), ('chemical_engineer', 'CHEMICAL_ENGINEER'), ('hotel_manager', 'HOTEL_MANAGER'), ('dentist', 'DENTIST'), ('comedian', 'COMEDIAN'), ('biomedical_engineer', 'BIOMEDICAL_ENGINEER'), ('graphic_designer', 'GRAPHIC_DESIGNER'), ('computer_hardware_engineer', 'COMPUTER_HARDWARE_ENGINEER'), ('petroleum_engineer', 'PETROLEUM_ENGINEER'), ('secretary', 'SECRETARY'), ('computer_operator', 'COMPUTER_OPERATOR'), ('chartered_accountant', 'CHARTERED_ACCOUNTANT'), ('technician', 'TECHNICIAN'), ('microbiologist', 'MICROBIOLOGIST'), ('fashion_designer', 'FASHION_DESIGNER'), ('aviator', 'AVIATOR'), ('psychologist', 'PSYCHOLOGIST'), ('magistrate', 'MAGISTRATE'), ('lawyer', 'LAWYER'), ('firefighter', 'FIREFIGHTER'), ('engineer', 'ENGINEER'), ('official', 'OFFICIAL'), ('analyst', 'ANALYST'), ('geologist', 'GEOLOGIST'), ('drafter', 'DRAFTER'), ('statistician', 'STATISTICIAN'), ('web_designer', 'WEB_DESIGNER'), ('consultant', 'CONSULTANT'), ('chef', 'CHEF'), ('army_officer', 'ARMY_OFFICER'), ('surgeon', 'SURGEON'), ('scientist', 'SCIENTIST'), ('civil_engineer', 'CIVIL_ENGINEER'), ('industrial_engineer', 'INDUSTRIAL_ENGINEER'), ('technology_specialist', 'TECHNOLOGY_SPECIALIST')], max_length=50)),
                ('experience', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('marital', models.CharField(max_length=266)),
                ('house', models.CharField(max_length=266)),
                ('car', models.CharField(max_length=266)),
                ('prediction', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
