# Generated by Django 4.2.3 on 2023-07-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_loan_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='profession',
            field=models.CharField(choices=[('mechanical_engineer', 'MECHANICAL_ENGINEER'), ('software_developer', 'SOFTWARE_DEVELOPER'), ('technical_writer', 'TECHNICAL_WRITER'), ('civil_servant', 'CIVIL_SERVANT'), ('librarian', 'LIBRARIAN'), ('economist', 'ECONOMIST'), ('flight_attendant', 'FLIGHT_ATTENDANT'), ('architect', 'ARCHITECT'), ('designer', 'DESIGNER'), ('physician', 'PHYSICIAN'), ('financial_analyst', 'FINANCIAL_ANALYST'), ('air_traffic_controller', 'AIR_TRAFFIC_CONTROLLER'), ('politician', 'POLITICIAN'), ('police_officer', 'POLICE_OFFICER'), ('artist', 'ARTIST'), ('surveyor', 'SURVEYOR'), ('design_engineer', 'DESIGN_ENGINEER'), ('chemical_engineer', 'CHEMICAL_ENGINEER'), ('hotel_manager', 'HOTEL_MANAGER'), ('dentist', 'DENTIST'), ('comedian', 'COMEDIAN'), ('biomedical_engineer', 'BIOMEDICAL_ENGINEER'), ('graphic_designer', 'GRAPHIC_DESIGNER'), ('computer_hardware_engineer', 'COMPUTER_HARDWARE_ENGINEER'), ('petroleum_engineer', 'PETROLEUM_ENGINEER'), ('secretary', 'SECRETARY'), ('computer_operator', 'COMPUTER_OPERATOR'), ('chartered_accountant', 'CHARTERED_ACCOUNTANT'), ('technician', 'TECHNICIAN'), ('microbiologist', 'MICROBIOLOGIST'), ('fashion_designer', 'FASHION_DESIGNER'), ('aviator', 'AVIATOR'), ('psychologist', 'PSYCHOLOGIST'), ('magistrate', 'MAGISTRATE'), ('lawyer', 'LAWYER'), ('firefighter', 'FIREFIGHTER'), ('engineer', 'ENGINEER'), ('official', 'OFFICIAL'), ('analyst', 'ANALYST'), ('geologist', 'GEOLOGIST'), ('drafter', 'DRAFTER'), ('statistician', 'STATISTICIAN'), ('web_designer', 'WEB_DESIGNER'), ('consultant', 'CONSULTANT'), ('chef', 'CHEF'), ('army_officer', 'ARMY_OFFICER'), ('surgeon', 'SURGEON'), ('scientist', 'SCIENTIST'), ('civil_engineer', 'CIVIL_ENGINEER'), ('industrial_engineer', 'INDUSTRIAL_ENGINEER'), ('technology_specialist', 'TECHNOLOGY_SPECIALIST')], default='mechanical_engineer', max_length=50),
        ),
    ]
