# Generated by Django 4.2.3 on 2023-07-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_loan_prediction_alter_loan_car_alter_loan_marital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='marital',
            name='name',
            field=models.PositiveIntegerField(choices=[(0, 'Married'), (1, 'Single')]),
        ),
    ]
