# Generated by Django 4.2.3 on 2023-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_marital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marital',
            name='name',
            field=models.PositiveIntegerField(choices=[(0, 'Married'), (1, 'Single')]),
        ),
    ]
