# Generated by Django 4.2.3 on 2023-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_marital_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='loan',
            name='car',
            field=models.CharField(max_length=266),
        ),
        migrations.AlterField(
            model_name='loan',
            name='marital',
            field=models.CharField(max_length=266),
        ),
        migrations.AlterField(
            model_name='marital',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
