# Generated by Django 4.2.3 on 2023-07-22 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_car_name_alter_loan_car_alter_loan_marital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
