# Generated by Django 4.2.3 on 2023-07-22 14:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_loan_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='profession',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
