# Generated by Django 4.2.3 on 2023-07-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_loan_amount_alter_loan_city_alter_loan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='profession',
            field=models.FloatField(choices=[(0, 'Mechanical_engineer'), (1, 'Software_Developer'), (2, 'Technical_writer'), (3, 'Civil_servant')], null=True),
        ),
    ]
