# Generated by Django 4.2.3 on 2023-07-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_loan_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='car',
            field=models.FloatField(choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='city',
            field=models.FloatField(choices=[(0, 'rural'), (1, 'urban')], null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='house',
            field=models.FloatField(choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='marital',
            field=models.FloatField(choices=[(0, 'single'), (1, 'married')], null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.FloatField(choices=[(0, 'no'), (1, 'yes')], null=True),
        ),
    ]
