# Generated by Django 4.2.3 on 2023-07-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_alter_loan_car_alter_loan_city_alter_loan_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='profession',
            field=models.FloatField(choices=[(0, 'Mechanical_engineer'), (1, 'Software_Developer')], null=True),
        ),
    ]
