# Generated by Django 4.2.3 on 2023-07-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_alter_loan_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='car',
            field=models.CharField(max_length=266),
        ),
        migrations.AlterField(
            model_name='loan',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='house',
            field=models.CharField(max_length=266),
        ),
        migrations.AlterField(
            model_name='loan',
            name='marital',
            field=models.CharField(max_length=266),
        ),
        migrations.AlterField(
            model_name='loan',
            name='profession',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='state',
            field=models.TextField(null=True),
        ),
    ]
