# Generated by Django 4.2.3 on 2023-07-24 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_alter_loan_car_alter_loan_city_alter_loan_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='city',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='state',
        ),
        migrations.AddField(
            model_name='loan',
            name='age',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AddField(
            model_name='loan',
            name='experience',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='loan',
            name='income',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
